# Generated by Django 3.0.5 on 2020-06-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='shippo_address_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
