# Generated by Django 3.0.5 on 2020-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_address_shippo_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='admin_address',
            field=models.BooleanField(default=False),
        ),
    ]
