apiVersion: v1
kind: Secret
metadata:
  name: apisecrets
type: Opaque
data:
  STRIPE_SECRET_KEY: c2tfbGl2ZV81MUdlbk5ZRkVRUlVKUGdQRFBwOFFPWm81a1ZIZGhYaHpiRWd0RHlPZ0pMOVNMWmlBMUVRZGZmckhIR1FXbTBuN29IY1BhWVBXNTV4RE1TN1NiY2FraVlHRTAwem9jS2NLYWc=
  STRIPE_PUBLISHABLE_KEY: cGtfbGl2ZV95MndpOW9pREJ3UXNRMXF2cVRsSGdWY1QwMEpUTXdraG5q 
  PLAID_CLIENT_ID: NWViZGMxZDJmNGUwMGQwMDEyNTZlNTgy
  PLAID_PUBLIC_KEY: OGM3ZTUzZWUxZmNjNTE0MjNjZDQxOTE4Mjc5NzNj
  PLAID_SECRET: NjFhZDU3MjVlYmIxYTliNWFlYWYyYjFlYWU1Mjgz
  PLAID_DEVELOPMENT_SECRET: ZDJiYzkxNGQ3NzM4NmJjYTgwODc0ZmQ5OWU4MGY5
  PLAID_ENVIRONMENT: UHJvZHVjdGlvbg==
  SHIPPO_API_KEY: c2hpcHBvX2xpdmVfM2QxZWI3NGNlOTQzNDM5NzEzODc3ODI5NDhjNTI0MmYxZDI3N2I1Mw==
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIzMDYzMDA4NzMzMDguZGtyLmVjci5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsaldHUnRVMFZvZDFOVll6VlBWbVJGVTJ4Q1JXTkdVWFpSTWxKcFVteE9hMU5xWkRSaVJWSnBWVmhLY1dKWE9ESlhVM1I2V21wc1RFOUVhSFpOYkU0MVYwaEtkMDFWWkUxaVNHaFpVV3RPU0UxdGEzbFpXSEEwVWtSQ1Yxa3piR2hqTTFweVYxWldOV0pHUW05Tk0yUmFVbXRrYmswd05WRmphMXBGVFhwV1MyRkdUa2xhTVhCdFUxVjBObUZUZEVWVVdGSkpUbTE0TWxwc1JYSlNSbkJLV1ZaVmVHUnFhRWRrYXpGeFVtNUdXbGRJYUVsVFZFb3dXVEpzYmxOR2F6TmxhMVp5VFROV1EySlVUbGhNTUdSSlVtMWFUR0ZZY0hOTlZURllUVzFPTlUweVRUSmlSMDB3WTIxR2JsSnRiSGRTTUVwVVZESm9WRlJGTVVOTlJsSjFWREE1TTFFeVpGaGFiV3hVVFRBNWFGRnVhelZpUlRGRFZVUmplR0ZIY0U5amJrcFBWVEpOZVZWRk1EVmxSMWsxWTI1U01WUjZVblZsYW1oTldsVk9jMDFHVG1GT2JFWndWREZXZFZkclpFWk5hemsxWlc1TmRtRkhNVFZaTVVKRVlWYzFUMUl5VGsxVFNGWkNVakJHVEZJemFEQlRSelI1VWpOR2VWSnNaSEZVV0c4eVZHdGFUbFV6U20xaGEwWjNZMFJvVVZsdFNUQk5Sa3BWVW0xU2JXTnJNWGxQUnpGVFRESktORlZzV25oT1YzUktaR2x6TWt3eFpFSlhWRWw1VmpGYVVVNHlOVk5sVnpsUlUxWnNVMVZJUWt4T00wMTJUVEZTTmxNeVpIRmhWa1pYVkZodk1GRnRiREZpUjFveFVtMDBkazFHU2tKaWJWRTBUVlU0TWxveU5ETlBWR3hWVmxSamQxUXpXbTFQVkZKNVVXNU9lR0pYYjNwWk0zQk5WakowYkZWdVJrdFVSMXBNVERCR1JVMXFWbXBSZW14MFZXMXpNRlF4U2pGaFYzUlFZekJyTTFwWGVETlNSRlpUVDFWS1JsbHJUbWxVTUhnelRUQk9SRnBZUW1sTmFtUlRZVlZzUlZKclNrWk9NbWh4WVZSS1JtTkZaREpTYmtKaFZUTmtTRkZyWkhWVWJsWlJVMnQ0VG1WdFpGbFhSMmh6Vkcxd1NGbFlaelJpTUhCdVkyNWtVMWRIT1hsVlJteFpUVVpHZEU1WVFUTlZSM0JMVlVNNVRGWnJjREpNTTFacFRrVjBhVnBFUWsxYVNFcEdVMnBTVmxaR1RYcFZSR3cxWVZWSmVXTkhOVzFhTTJSeFYxaGpkbEp0VFhKaVJYUjRZekpaZDFGVlJtdFdiV1F3VFVkbk1Fc3hVa2xTYTAwMVRUQmpNVmRITlhSbGEzaE5WMGR3ZEZkVk9WcFVNMHBMVkZkNE5HSXhaek5pYTBwUVZVVXhXR05YUmxaak1YQk1VVEJrV2sxRk9VdGtSVW8xV2xoc2FsSXpaRzlVVnpCeVYxWndkR1ZZVlRSWFNGSmFWVVZzVkdKck5YRlpNRTR4VTFkT2FWbFlVblZWYkZaRFZERlNhRmw2V210U01HZzFVa1pqTTFGWVZteFZWMDR6VTNsMFExSkZNVWhPTVdSWFRXMWFkRkpwZEhkWFZ6VnVXV3BLZUV3d2RHNVVlbVF5VWpCa1EyRkhVbkZoU0VKU1ZXeFdiVTU2YkhkT01tTjRZa1JTYjA1cVFsQlZha2wzV2tkYWJGUnFhR2hTUlVaT1YxWkplVmRHYkVwU2F6VXlXakpPTlZaSVFsZFVTRnBSWVVoYVJXUnRTbFJPVjA1UVQxUnNSMHN5YUU5T2EzaHRXbFphZDJWR2JGVlJiRXBLVWtkc2FVMUhTVEJpVlc4eFRUTldWR1ZGWkVObFZUUTBZbTVXVFZONlpHcE9ibXhVVERGa2VXTXliekpYVlRWT1lteENjVTVHUmxOalZXeFhaVmhzY1dFemF6SlJNV1I1V2xob01rNVhVbTlVYmtacllqTm9URTlJUmtwT1JFWndWMFZhTUZrd2RHdGFWMFpJV2pOV1lXUklTbEJWYms0eFV6Qk9XRkpHUW14UFZscE9ZVlJvU1ZkRlRsSmhhMHA1VmxOMFRsb3hVakpPTTBaWlRraEtjMkZ1WkVOV1ZuQldWbTFXVWxaSWNGQldSVTVPV2pGV2NrMXVVa0pWVmxadlpHdGtWVk5UY3pCbFJsWlFWMWRHVEZWdFdrTmFSR1JwWlVjMVQwNVdhRk5XVjFaS1V6TkdlVkl3ZEhaWmJGcHVUa1ZTTTFkRmN6UmpNMnhZVmtWT1ZsUjZhRWRsYmtKUVltMXNRMDVyZUVaT2FYUjFUbFJXV1dNeGJEWlNTRXB4VkZWdmQxZEhVa3RWTTFwRVYxTTVTMDFWWkRWT1JHaFZZVzF3TWxGVmN6VlVWVzh5WVZSamVFMVliRmRTVlhodVRtMHhRMDE2YkdGV01qazFUbnBTZWxwclVrZFVWbkJLWWxab2NXSnJiSFphZW14R1ZrZEdOV0pVYUZka1YyUk5WVEpOZUZSRldsVkxNVloyWkcxU1QxTllVVEJoTVUxNlRXNU9jRTFxVGtWVWFUbEpUV3BWTWxvelRURlhhelUwVkRKb2JWRnFSbUZOYW1oSlZWVkpNMXBYYjNkVU1HTnlWMGhqT1VscGQybGFSMFl3V1ZkMGJHVlRTVFpKYTBaU1VsVktRbE5IYUU5U1NIQllWbTAxV2xJemJITlRlazR3VmxkR2MxTkZSazlqUnpGNVlteEdObGxVVmpOT1JtTXdXVEJvV2xSV1ZUUk5ibEpwVkd0c00xRlZSa0pUUkZJeldtdEdXbE5yZEhaWGEyeHZaRzFPVDFGV1JtcFNNamxJVDBoa2FWVlZiRU5SVlZKRFlqQktibUV6Um05aE1teElUMWhqZDFGclNqTlNXR1JKV2pGc1MxZFZiR0ZUVlVaWVZsVlNRMUZWVmpGVVZVcEdVbFZTVUdNemJGVkxNbWh0WTBjME1HVlZSbmhOUlRGWlVWVnNRMUpWYkVKT01XUldaRE5TZGxaWGFGbE9SVXB2VkZWVk1GVlZOVU5TTVdoTFQwZFNRazV0ZUhGYWJHeFBWa1prYUZaV1ZYaGxhbG96VjJwV2VGZFhPRFJhYkVadFZrVm9WMk51YUhKaWJrcGhWR3RzY1ZGc1VYaExNazU1VW1wQ01XTXdWa3RoYlRsT1lUQTFjRlV4UlRsSmFYZHBaRzFXZVdNeWJIWmlhVWsyU1dwSmFVeERTakJsV0VKc1NXcHZhVkpGUmxWUlZqbE1VbFpyYVV4RFNteGxTRUp3WTIxR01HRlhPWFZKYW05NFRsUnJkMDFVUlhoT2FrMHhabEU5UFE9PSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuOSAobGludXgpIgoJfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: payouttt
  name: payouttt
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payouttt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: payouttt
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: regcred
      containers:
      - image: 306300873308.dkr.ecr.us-east-1.amazonaws.com/payouttt-django-backend-us:test
        command: ["/bin/sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]
        envFrom:
          - secretRef:
              name: apisecrets 
        ports:
        - containerPort: 8000
        name: payouttt
        imagePullPolicy: Always
