apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: payouttt
  name: payouttt
spec:
  replicas: 1
  selector:
    matchLabels:
      run: payouttt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: payouttt
    spec:
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      containers:
      - image: 306300873308.dkr.ecr.us-east-1.amazonaws.com/payouttt-django-backend-us:62cf6690
        command: ["/bin/sh", "-c", " python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic && /etc/init.d/nginx restart && gunicorn Payouttt.wsgi:application -b 0.0.0.0:8000 "]
        env:
                #   - name: DJANGO_APP_STATIC_URL
                #   value: s3://staticfilesv1/staticfiles/
         - name: POSTGRES_DB
           value: payouttt_portal
         - name: POSTGRES_PASSWORD
           value: password1234
         - name: DEBUG
           value: '0'
         - name: POSTGRES_HOST
           value: postgres
        envFrom:
          - secretRef:
              name: apisecrets 
        ports:
        - containerPort: 80
        name: payouttt
        imagePullPolicy: Always
