FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
EXPOSE 8000
COPY requirements.txt /code/
RUN pip3 install -r requirements.txt
COPY . /code/
ENV  STRIPE_SECRET_KEY="c2tfbGl2ZV81MUdlbk5ZRkVRUlVKUGdQRFBwOFFPWm81a1ZIZGhYaHpiRWd0RHlPZ0pMOVNMWmlBMUVRZGZmckhIR1FXbTBuN29IY1BhWVBXNTV4RE1TN1NiY2FraVlHRTAwem9jS2NLYWc="
ENV  STRIPE_PUBLISHABLE_KEY="cGtfbGl2ZV95MndpOW9pREJ3UXNRMXF2cVRsSGdWY1QwMEpUTXdraG5q" 
ENV  PLAID_CLIENT_ID="NWViZGMxZDJmNGUwMGQwMDEyNTZlNTgy"
ENV  PLAID_PUBLIC_KEY="OGM3ZTUzZWUxZmNjNTE0MjNjZDQxOTE4Mjc5NzNj"
ENV  PLAID_SECRET="NjFhZDU3MjVlYmIxYTliNWFlYWYyYjFlYWU1Mjgz"
ENV  PLAID_DEVELOPMENT_SECRET="ZDJiYzkxNGQ3NzM4NmJjYTgwODc0ZmQ5OWU4MGY5"
ENV  PLAID_ENVIRONMENT="UHJvZHVjdGlvbg=="
ENV  SHIPPO_API_KEY="c2hpcHBvX2xpdmVfM2QxZWI3NGNlOTQzNDM5NzEzODc3ODI5NDhjNTI0MmYxZDI3N2I1Mw=="

CMD python3 manage.py migrate &&  python3 manage.py runserver 0.0.0.0:8000
