apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      run: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: postgres
    spec:
      hostname: postgres
      terminationGracePeriodSeconds: 5
      containers:
      - image: postgres:10.4
        env: 
        - name: POSTGRES_DB
          value: "Payouttt_portal"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1234"
        ports:
        - containerPort: 5432
        name: postgres
        imagePullPolicy: Always
