# Generated by Django 3.0.5 on 2020-09-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200922_1249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200716_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refunded', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
