# Generated by Django 3.0.5 on 2020-05-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_sizes',
            field=models.ManyToManyField(blank=True, null=True, to='api.ShoeSize'),
        ),
    ]
