# Generated by Django 3.0.5 on 2020-05-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200507_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoesize',
            unique_together={('country', 'shoe_size')},
        ),
    ]
