# Generated by Django 3.0.5 on 2020-05-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200503_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpayment',
            name='buyer_shippo_error',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bidpayment',
            name='seller_purchase_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bidpayment',
            name='seller_shippo_error',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bidpayment',
            name='seller_tracking',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
