# Generated by Django 3.0.5 on 2020-05-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200503_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpayment',
            name='seller_success_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
