# Generated by Django 3.0.5 on 2020-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bidpayment_seller_success_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidpayment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('dwolla', 'Dwolla')], default='dwolla', max_length=10),
        ),
    ]
