# Generated by Django 3.0.5 on 2020-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidpayment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('dwolla', 'Dwolla'), ('plaid', 'Plaid')], default='dwolla', max_length=10),
        ),
    ]
