# Generated by Django 3.0.5 on 2020-05-28 20:11

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Bid = apps.get_model('api', 'Bid')
    for bid in Bid.objects.all():
        bid.order_id = uuid.uuid4()
        bid.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_auto_20200526_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
        migrations.RunPython(create_uuid),
    ]
