# Generated by Django 3.0.5 on 2020-06-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200528_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('seller_send', 'Seller Send'), ('payout_received', 'Payouttt Received'), ('payout_send', 'Send from Payouttt')], default='seller_send', max_length=20)),
                ('status_message', models.CharField(max_length=200)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bid')),
            ],
            options={
                'unique_together': {('bid', 'status')},
            },
        ),
    ]
