# Generated by Django 3.0.5 on 2020-06-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bidstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
