# Generated by Django 3.0.5 on 2020-08-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200805_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
