# Generated by Django 3.0.5 on 2020-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200806_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='shippo_error',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
