# Generated by Django 3.0.5 on 2020-09-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidstatus',
            name='status',
            field=models.CharField(choices=[('seller_send', 'Seller Send'), ('payout_received', 'Payout Received'), ('payout_send', 'Send from QuickKicks')], default='seller_send', max_length=20),
        ),
    ]
