# Generated by Django 3.0.5 on 2021-02-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200922_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidstatus',
            name='status',
            field=models.CharField(choices=[('seller_send', 'Seller Send'), ('payout_received', 'Payout Received'), ('payout_send', 'Send from Payouttt')], default='seller_send', max_length=20),
        ),
    ]
