# Generated by Django 3.0.5 on 2020-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
