# Generated by Django 3.0.5 on 2020-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fundingsource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
