# Generated by Django 3.0.5 on 2020-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200512_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_payment_method',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
