# Generated by Django 3.0.5 on 2020-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200512_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('account_id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
