# Generated by Django 3.0.5 on 2020-05-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_plaid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plaid',
        ),
    ]
