# Generated by Django 3.0.5 on 2020-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_plaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaid',
            name='item_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
